image: ubuntu:zesty

pipelines:
  default:
    - step:
        script:
          - apt update
          - apt -y install dirmngr
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable zesty main" > /etc/apt/sources.list.d/gazebo-stable.list
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-prerelease zesty main" > /etc/apt/sources.list.d/gazebo-prerelease.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt-get update
          - apt-get -y install
            cmake pkg-config python ruby-ronn uuid-dev
            libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev
            libfreeimage-dev libgts-dev libswscale-dev libtinyxml2-dev
            libignition-cmake-dev
            libignition-math4-dev
            lcov curl mercurial cppcheck
          # Code checker
          - sh tools/code_check.sh
          # Build
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          # Tests
          - make test
          - make install
          # Coverage
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          # Examples
          - cd ../examples
          - mkdir build
          - cd build
          - cmake ..
          - make
